[2023-10-16 21:22:01,179] WARN [AdminClient clientId=adminclient-1] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
Topic: ECOMMERCE_ORDER_APPROVED	TopicId: 5ydpP9X4RTC89DRMFkwzBA	PartitionCount: 1	ReplicationFactor: 1	Configs: 
	Topic: ECOMMERCE_ORDER_APPROVED	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
Topic: ECOMMERCE_SEND_EMAIL	TopicId: LO_HDy6gQaua_SYfv2OAsg	PartitionCount: 1	ReplicationFactor: 1	Configs: 
	Topic: ECOMMERCE_SEND_EMAIL	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
Topic: ECOMMERCE_ORDER_REJECTED	TopicId: 2OAFEeUZTE620my4u5BtxA	PartitionCount: 1	ReplicationFactor: 1	Configs: 
	Topic: ECOMMERCE_ORDER_REJECTED	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
Topic: ECOMMERCE_NEW_ORDER	TopicId: H2VD8B-BQRWix-0q2myi3A	PartitionCount: 1	ReplicationFactor: 1	Configs: 
	Topic: ECOMMERCE_NEW_ORDER	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
Topic: __consumer_offsets	TopicId: FlU5RWr-R06NDidr-U7Ixw	PartitionCount: 50	ReplicationFactor: 1	Configs: compression.type=producer,cleanup.policy=compact,segment.bytes=104857600
	Topic: __consumer_offsets	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 1	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 2	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 3	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 4	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 5	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 6	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 7	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 8	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 9	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 10	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 11	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 12	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 13	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 14	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 15	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 16	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 17	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 18	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 19	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 20	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 21	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 22	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 23	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 24	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 25	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 26	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 27	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 28	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 29	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 30	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 31	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 32	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 33	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 34	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 35	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 36	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 37	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 38	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 39	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 40	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 41	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 42	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 43	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 44	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 45	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 46	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 47	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 48	Leader: 1	Replicas: 1	Isr: 1
	Topic: __consumer_offsets	Partition: 49	Leader: 1	Replicas: 1	Isr: 1
